--- 
- name: Installing php.info
  hosts: all 
  become: yes
  vars:
    php_file_path: ./info.php
    php_file_destination: /var/www/html/info.php
  tasks:
    - name: using debug
      ansible.builtin.debug:
        msg: Updating ubuntu packages and Installing apache2
    - name: updating the packages and installing apache2
      ansible.builtin.apt:
        name: 
          - apache2
          - php 
          - libapache2-mod-php 
          - php-mysql
        update_cache: yes
        state: present
    - name: using debug
      ansible.builtin.debug:
        msg: copying info.php to node 
    - name: copying info.php file
      ansible.builtin.copy:
        src: "{{ php_file_path }}" 
        dest: "{{ php_file_destination }}"
    - name: using debug
      ansible.builtin.debug:
        msg: starting apache2 service    
    - name: starting apache2
      ansible.builtin.systemd:  
        name: apache2
        enabled: yes
        state: started    